# Generated by Django 5.0.3 on 2024-04-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurantPlace", models.CharField(max_length=200)),
                ("restaurantName", models.CharField(max_length=200)),
                ("openDate", models.CharField(max_length=200)),
                ("useStartTime", models.CharField(max_length=200)),
                ("useEndTime", models.CharField(max_length=200)),
                ("breakStartTime", models.CharField(max_length=200)),
                ("breakEndTime", models.CharField(max_length=200)),
                ("foodType", models.CharField(max_length=200)),
                ("restaurantNumber", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
    ]
